version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    labels:
      - "traefik.http.routers.frontend.rule=Host(`app.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend-old.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend-new.rule=Host(`newapp.localhost`)"
      - "traefik.http.middlewares.redirect-to-app.redirectregex.regex=^https://newapp.localhost(.*)"
      - "traefik.http.middlewares.redirect-to-app.redirectregex.replacement=https://app.localhost$${1}"
      - "traefik.http.middlewares.redirect-to-app.redirectregex.permanent=true"
      - "traefik.http.routers.frontend-new.middlewares=redirect-to-app"
    depends_on:
      - traefik
      - backend
      
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ]
      timeout: 10s
      retries: 5
  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    restart: 'always'
    # ...
    labels:
      - "traefik.http.routers.backend.rule=(Host(`api.app.localhost`) && PathPrefix(`/api`))"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.routers.backend-old.tls.certresolver=myresolver"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend-new.rule=(Host(`api.newapp.localhost`) && PathPrefix(`/api`))"
      - "traefik.http.middlewares.redirect-to-api.redirectregex.regex=^https://api.newapp.localhost(.*)"
      - "traefik.http.middlewares.redirect-to-api.redirectregex.replacement=https://api.app.localhost$${1}"
      - "traefik.http.middlewares.redirect-to-api.redirectregex.permanent=true"
      - "traefik.http.routers.backend-new.middlewares=redirect-to-api"
    depends_on:
      - db
      - traefik
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=anis@123
      - DB_HOST=db
      - DB_NAME=todolist
      - DB_PORT=3306
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    platform: linux/x86_64 
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=anis@123
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
  traefik:
    image: traefik:v2.9
    command: 
    - "--api.insecure=true"
    - "--providers.docker=true"  
    #- "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - --certificatesresolvers.myresolver.acme.tlschallenge=true
    - --certificatesresolvers.myresolver.acme.email=your-email@example.com
    - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"