version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    labels:
      - "traefik.http.routers.frontend.rule=Host(`app.localhost`)"
    depends_on:
      - traefik
      - backend
      
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ]
      timeout: 10s
      retries: 5
  backend:
    build: ./backend
    container_name: app_backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    restart: 'always'
    # ...
    labels:
      - "traefik.http.routers.backend.rule=(Host(`api.app.localhost`) && PathPrefix(`/api`))"
    depends_on:
      - db
      - traefik
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=anis@123
      - DB_HOST=db
      - DB_NAME=todolist
      - DB_PORT=3306
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    platform: linux/x86_64 
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=anis@123
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
  traefik:
    image: traefik:v2.9
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock